// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MoonPhases
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("phase")]
        public string Phase { get; set; }

        [JsonProperty("phaseEmoji")]
        public string PhaseEmoji { get; set; }

        [JsonProperty("illumination")]
        public double? Illumination { get; set; }

        [JsonProperty("waxing")]
        public bool? Waxing { get; set; }

        [JsonProperty("waning")]
        public bool? Waning { get; set; }

        [JsonProperty("lunarAge")]
        public double? LunarAge { get; set; }

        [JsonProperty("lunarAgePercent")]
        public double? LunarAgePercent { get; set; }

        [JsonProperty("lunationNumber")]
        public long? LunationNumber { get; set; }

        [JsonProperty("lunarDistance")]
        public double? LunarDistance { get; set; }

        [JsonProperty("nextFullMoon")]
        public DateTimeOffset? NextFullMoon { get; set; }

        [JsonProperty("lastFullMoon")]
        public DateTimeOffset? LastFullMoon { get; set; }

        [JsonProperty("daysToFullMoon")]
        public long? DaysToFullMoon { get; set; }

        [JsonProperty("daysSinceFullMoon")]
        public long? DaysSinceFullMoon { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
